### ISSUE TITLE
Can't seem to 'Flexi Edit' Bezier curves after creation.

### ISSUE THREAD

**Issue by mcolinp** [Shriinivas/blenderbezierutils#3]
I have been trying and trying to edit curves I have drawn in draw mode using the Flexi Draw Bezier tool. When I try to activate the 'Flexi Edit Bezier' Tool; the curves then show a green highlight around them, and do not show the blue sections as shown in the documentation video. And clicking on the curves never reveals any Bezier handles to move or manipulate. If I do click and drag; it just changes to the 'Move' tool, and moves the entire grease pencil object.

Not sure if this is a bug, or if I am doing something wrong.  

I also do not get the select tool box that shows up with Shift+Spacebar. I tried deleting some of my keybindings to get that to work; but it never shows up. 

I would suggest allowing the user to setup their own keybindings per tool (in the preferences panel>Add-ons>Bezier Utilities.); instead of everything being locked down. Perhaps a pie menu would be a nice enhancement as well.

**Comment by Shriinivas** [comment]
There are actually two tools for creating Bezier curves 1) Flexi Draw Bezier (available in Object mode): https://youtu.be/C9PXp0XHgYQ 2) Flexi Grease Bezier (available in Draw mode): https://youtu.be/4XrjpWwLU4M
You won't be able to edit the Grease Bezier strokes as Bezier curves with handles because they are not stored as Bezier curves but as line segments. The curves that you see in the video are created using the Flexi Draw Bezier (in object mode). Or you will be able to edit Bezier Circles or Bezier Curves added from Add->Curve menu. 

About the user configurable keybindings, yes, that's on the plan. ETA cannot be given at this moment, though.

**Comment by mcolinp** [comment]
I have also since reading both your replies; confirmed that I am unable to Flexi Edit Curves drawn with the Flexi Draw Bezier tool. While I can turn it to edit mode; I am unable to use the specific Flexi edit toll in object mode as your videos demonstrate. Not sure what I'm missing here.

**Comment by mcolinp** [comment]
In fact; in Object mode; it won't allow me to draw Flexi Beziier curves either; when starting in the 'General' normal 3D startup using the Layout workspace. (My workspaces definitely are not the same as the factory defaults.) But I am simply illustrating that I was not starting out in the '2D Animation' workspace either.

**Comment by mcolinp** [comment]
Upon further research, I found it behaves the way you demonstrated, when I re-load factory settings. I will one by one try and see if I can narrow down which add-on or setting is interfering with it and report back.

**Comment by mcolinp** [comment]
Looks like the issue is Key-Binding related. I tried making a new workspace and filtering all add-ons off; except 'Bezier Utilities'. It still did not want to work with the 'Flex Edit' mode. 

The next step was to save my Key-Bindings, and then choose 'Blender' keybindings from the choices in the drop-down (In Preferences>Keymap panel at the top). When I did this; it worked as expected.

**Comment by Shriinivas** [comment]
Thank you for your inputs. They are helpful to me. It may be better though, if you could directly email them to me at khemadeva@gmail.com instead of putting them here. Because they seem to be specific to your installation and this space is kind of for more generic issues.
As for the proxy link, the problem with it is that if the user edits the grease pencil stroke, converting it back to a 'clean' Bezier is rather tedious and may not be lossless. Blender team may already be working on this, I saw a request from one of the users that amounted to more or less what you said.
